[package]
name = "rust"
version = "0.1.0"
authors = ["Emerson Harkin <emerson.f.harkin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5 = "0.5.2"
ndarray = "0.13.0"
